server:
  port: 8080
# 连接池配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql:///hm_dianping
      username: root
      password: liuning19881117
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    # host: 101.37.84.243
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  rabbitmq:
    host: 101.37.84.243
    username: admin
    password: admin
    virtual-host: /admin
    port: 5672
    listener: # 监听操作
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
        auto-startup: true
        default-requeue-rejected: true
        acknowledge-mode: auto
        retry:
          enabled: true # 消费者开启重试机制
          max-attempts: 3
          stateless: true # true 是无状态 false 是有状态 如果业务中有事务的话开启有状态false
    connection-timeout: 1s
#    template: # 连接操作
#      retry:
#        enabled: true #开启超时重试机制
#        initial-interval: 1000ms # 初始等待时间
#        max-attempts: 3 # 最大重试次数
#        max-interval: 10000ms # 最大的等待时间
#        multiplier: 1 # 失败倍数的累加时间
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug